# Site settings
title: "Magpie: Oncoblocks Genomic Data Warehouse"
email: "willoemler@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  "Magpie is the Oncoblocks Genomic Data Warehouse project for Google Summer of Code 2015.""
baseurl: "/magpie" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: "woemler"
github_username:  "woemler"

# Build settings
markdown: kramdown
